# ====================== Kitty Configuration ======================

confirm_os_window_close 0
enable_audio_bell no

# ==================== Window ====================
window_padding_width 16 0
dynamic_padding yes
background_opacity 0.98

# ==================== Font ====================
font_family      MesloLGS NF
bold_font        MesloLGS NF Bold
italic_font      MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic

font_size 11.0

# ==================== Colors ====================
background #161616
foreground #ffffff

cursor            #FFC996
cursor_text_color #161616

selection_foreground #161616
selection_background #FFEDA3

# Normal colors
color0  #161616
color1  #f26d8c
color2  #ACFFAD
color3  #FDFFB6
color4  #A3A0FF
color5  #6dcbf9
color6  #99EBFC
color7  #d1d1d1

# Bright colors
color8  #5e6377
color9  #f26d8c
color10 #ACFFAD
color11 #FFEDA3
color12 #A3A0FF
color13 #6dcbf9
color14 #99EBFC
color15 #d1d1d1

# ==================== Cursor ====================
cursor_shape underline
cursor_blink_interval 0.75

# ==================== Scrolling ====================
scrollback_lines 5000

# ==================== Keybindings ====================
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+equal  change_font_size +2
map ctrl+minus  change_font_size -2
map ctrl+0      change_font_size 0

map f11 toggle_fullscreen

map ctrl+l combine : clear_terminal scrollback : send_text normal \x0c
