#! /bin/sh

# ~/.config/bspwm/bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI #VII VIII IX X
bspc monitor -d      

bspc config window_gap          4
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"#7fd4ff"
bspc config normal_border_color		"#18181c"
bspc config border_width        0

bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a Chromium-browser desktop='^3' follow=on 
bspc rule -a Midori desktop='^3' follow=on 
bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/sagb/Pictures/pokemonLake.jpg
bash ~/.config/polybar/launch.sh --forest 
picom --experimental-backends &
sh ~/.scripts/notification/hello.sh &
